### ISSUE TITLE
Improve the ui of the portfolio card when modal is close

### ISSUE THREAD

**Issue by bilalakhter** [bilalakhter/minimalist-template-portfolio#4]
it will be good if UI can be changed into more like this 
https://dribbble.com/shots/6247653-Info-Cards-Animation

**Comment by bilalakhter** [comment]
Thanks a lot

**Comment by Taejin101** [comment]
Do you need any help on this?

**Comment by abuna1985** [comment]
My apologies. I didn't realize it was assigned to me until today. I can do a PR with the next few days.

**Comment by bilalakhter** [comment]
i was hoping significant changes but anyways i have merged it @Muratozbk

**Comment by bilalakhter** [comment]
go ahead @Taejin101

**Comment by Taejin101** [comment]
I am new to open source. I don't know where to start with.

**Comment by Muratozbk** [comment]
thx @bilalakhter , it was my first pull request and I did a small touch.

**Comment by Siddhesh-Agarwal** [comment]
@abuna1985 Can I try it? Also, this effect is meant to be added to the "skill" cards, right?

**Comment by bilalakhter** [comment]
no @Siddhesh-Agarwal  only the portfolio cards

**Comment by bilalakhter** [comment]
sure you can try
