### ISSUE TITLE
Navbar links not mapped correctly

### ISSUE THREAD

**Issue by Siddhesh-Agarwal** [bilalakhter/minimalist-template-portfolio#8]
**Describe the bug**
The links in the Navbar are not mapped/linked correctly.
- `Home` is linked to `#hero`
- `Skill` is linked to `#about`
- `Portfolio` is linked to `#skills`
- `Experience` is linked to `#services`

**Expected behaviour**
- `Home` should be linked to `#home`
- `Skill` should be linked to `#skills`
- `Portfolio` should be linked to `#portfolio`
- `Experience` should be linked to `#experience`

**Comment by bilalakhter** [comment]
sure you can fix this

**Comment by bilalakhter** [comment]
thanks
